In [1]:
import numpy as np
import scipy as sp
from flask import Flask
import pandas as pd

https://physics.nist.gov/PhysRefData/ASD/lines_form.html

In [ ]:
from scipy import special

# Define parameters for the spherical harmonic function
m = 0  # Order (integer, |m| <= n)
n = 2  # Degree (integer, n >= 0)
theta = np.linspace(0, np.pi, 100)  # Polar angle
phi = np.linspace(0, 2*np.pi, 100)  # Azimuthal angle

# Calculate the spherical harmonic values
Y = special.sph_harm(m, n, phi[:, np.newaxis], theta)

print(f"Calculated {Y.shape} spherical harmonic values for m={m}, n={n}")

In [ ]:
angularFunctions = pd.DataFrame({
    'l': [m],
    'n': [n],
    'theta': [theta.tolist()],
    'phi': [phi.tolist()],
    'Y': [Y.tolist()]
})

NameError: name 'm' is not defined

In [ ]:
radialFunctions = pd.DataFrame({
    'n': [1, 2, 2, 3, 3, 3],
    'l': [0, 0, 1, 0, 1, 2],
})
radialFunctions

   n  l  m  Z
0  1  0  0  1
1  2  0  0  1
2  2  1 -1  1
3  3  0  0  1
4  3  1  1  1
5  3  2  0  1

In [7]:
data = pd.read_csv('./data/spectrumHAR.csv')
data

,element,sp_num,obs_wl_vac(nm),unc_obs_wl,ritz_wl_vac(nm),unc_ritz_wl,obs-ritz,wn(cm-1),intens,Aki(s^-1),...,conf_i,term_i,J_i,conf_k,term_k,J_k,Type,tp_ref,line_ref,Unnamed: 22
0,Ar,18,"=""""","=""""","=""0.288103238""","=""0.000000003""","=""""","=""34709779.9""","=""""","=""2.0565e+12""",...,"=""1s""","=""2S""","=""1/2""","=""6p""","=""2P*""","=""1/2""",NaN,"=""T7771""","=""""",NaN
1,Ar,18,"=""""","=""""","=""0.291749237""","=""0.000000003""","=""""","=""34276010.8""","=""""","=""3.6034e+12""",...,"=""1s""","=""2S""","=""1/2""","=""5p""","=""2P*""","=""3/2""",NaN,"=""T7771""","=""""",NaN
2,Ar,18,"=""""","=""""","=""0.291770388""","=""0.000000003""","=""""","=""34273526.1""","=""""","=""3.5864e+12""",...,"=""1s""","=""2S""","=""1/2""","=""5p""","=""2P*""","=""1/2""",NaN,"=""T7771""","=""""",NaN
3,Ar,18,"=""""","=""""","=""0.298732543""","=""0.000000003""","=""""","=""33474759.3""","=""""","=""7.1479e+12""",...,"=""1s""","=""2S""","=""1/2""","=""4p""","=""2P*""","=""3/2""",NaN,"=""T7771""","=""""",NaN
4,Ar,18,"=""""","=""""","=""0.298775875""","=""0.000000005""","=""""","=""33469904.5""","=""""","=""7.1234e+12""",...,"=""1s""","=""2S""","=""1/2""","=""4p""","=""2P*""","=""1/2""",NaN,"=""T7771""","=""""",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6011,H,1,"=""25590000000.0""","=""30000000.0""","=""25640000000""","=""30000000""","=""-50000000""","=""0.0003907""","=""""","=""""",...,"=""9p""","=""2P*""","=""1/2""","=""9s""","=""2S""","=""1/2""",NaN,"=""""","=""L15291c33""",NaN
6012,H,1,"=""35100000000.0""","=""50000000.0""","=""34480000000""","=""50000000""","=""620000000""","=""0.0002849""","=""""","=""""",...,"=""10p""","=""2P*""","=""1/2""","=""10s""","=""2S""","=""1/2""",NaN,"=""""","=""L15291c33""",NaN
6013,H,1,"=""46710000000.0""","=""70000000.0""","=""45450000000""","=""60000000""","=""1260000000""","=""0.0002141""","=""""","=""""",...,"=""11p""","=""2P*""","=""1/2""","=""11s""","=""2S""","=""1/2""",NaN,"=""""","=""L15291c33""",NaN
6014,H,1,"=""55000000000.0""","=""9000000000.0""","=""56000000000""","=""6000000000""","=""-1000000000""","=""0.00018""","=""""","=""""",...,"=""3d""","=""2D""","=""3/2""","=""3p""","=""2P*""","=""3/2""",NaN,"=""""","=""L4386""",NaN
6015,H,1,"=""60640000000.0""","=""90000000.0""","=""62500000000""","=""90000000""","=""-1860000000""","=""0.00016491""","=""""","=""""",...,"=""12p""","=""2P*""","=""1/2""","=""12s""","=""2S""","=""1/2""",NaN,"=""""","=""L15291c33""",NaN